-- Gerado automaticamente por `apps/api/scripts/gerar-seed-conteudo-inicial.mjs`
-- a partir de `CONTENT_SECTIONS` (@ketochlor/content-schema). NÃO EDITE
-- ESTE ARQUIVO À MÃO — mude o conteúdo em `packages/content-schema/src/sections/*.ts`
-- e rode de novo:
--
--   npm run gerar-seed --workspace=@ketochlor/api
--
-- O Supabase CLI roda `supabase/seed.sql` automaticamente ao final de todo
-- `supabase db reset` (https://supabase.com/docs/guides/local-development/seeding-your-database),
-- depois de aplicar as migrations em `supabase/migrations/` — este arquivo
-- preenche com o conteúdo real as 11 linhas de `content_sections` que a
-- migration `20260908192455_create_content_sections.sql` cria com
-- `data = '{}'::jsonb`.
--
-- `ON CONFLICT ... DO UPDATE` (em vez de um `INSERT` simples) faz deste
-- script uma operação idempotente: rodar `supabase db reset` de novo, ou
-- reexecutar este `seed.sql` num banco que já tem as linhas, atualiza
-- `data` no lugar em vez de duplicar linha ou falhar por violação da chave
-- primária `key`. Só a coluna `data` é tocada — `is_published` e
-- `item_visibility` (edições feitas pelo painel) não são sobrescritas.
--
-- Ref.: agent_context/PLAN.md, tarefa `integracao/migracao-conteudo-inicial`.

insert into content_sections (key, data) values
  ('hero', '{"eyebrow":"CIÊNCIA QUE ACOLHE, CUIDADO QUE RESOLVE","heading":"Prepare-se para a evolução da terapia tópica.","subheading":"A concentração ideal de clorexidina recomendada pela diretriz ICAID (2025), associada ao Cetoconazol e tecnologia exclusiva de suporte ao microbioma cutâneo.","ctaLabel":"QUERO ACESSAR O MATERIAL TÉCNICO COMPLETO","logo":{"url":"/assets/logo-ketochlor-transp.png","alt":"Ketochlor®"},"imagemCampanha":{"url":"/assets/ketochlor-img-campanha.png","alt":"Linha Ketochlor® — shampoos terapêuticos Virbac"},"selo":{"url":"/assets/padrao-ouro.png","alt":"Selo Padrão Ouro Virbac"}}'::jsonb),
  ('problema', '{"eyebrow":"O PROBLEMA","heading":"O ciclo que se repete","paragraphs":["A Dermatite Atópica Canina (DAC) raramente aparece sozinha. A ruptura da barreira cutânea e outras alterações fisiológicas, levam à disbiose abrindo espaço para infecções secundárias – bacterianas e fúngicas – que se retroalimentam com o prurido e a inflamação de base.","O resultado, na prática clínica, é um ciclo recorrente: o tutor trata a crise, os sinais melhoram, e semanas depois o quadro retorna, muitas vezes mais intenso.","Romper esse ciclo exige controlar as duas frentes de infecção secundária ao mesmo tempo, e não apenas uma delas."],"imagem":{"url":"/assets/cachorro-cocando2.jpg","alt":"Cão apresentando prurido, sinal clínico de infecção secundária associada à DAC"}}'::jsonb),
  ('fenotipos', '{"eyebrow":"FENÓTIPOS DA DAC","heading":"Nem todo caso de DAC pede a mesma resposta","intro":"Pacientes atópicos não são todos iguais — e a literatura confirma o que a clínica já mostra. Segundo Ferreira et al. (2023)⁶, os fenótipos da DAC variam conforme as interleucinas produzidas e a fase da doença:","agudo":{"title":"Paciente agudo","subtitle":"Resposta Th2","body":"Pele eritematosa, prurido intenso, maior ocorrência de foliculite bacteriana superficial.","badge":"HEXADENE INDICADO"},"cronico":{"title":"Paciente crônico","subtitle":"Resposta Th1 + Th2","body":"Hiperqueratose, hiperpigmentação, infecções recorrentes com supercrescimento bacteriano (BOG) e de Malassezia spp. (MOG) — a Malasseziose.","badge":"KETOCHLOR® INDICADO"},"closing":"Ketochlor® foi indicado para o paciente crônico, com infecção recorrente por BOG e MOG⁶ — o caso em que a resposta precisa ser dupla, e não apenas antisséptica ou apenas antifúngica."}'::jsonb),
  ('mecanismo', '{"eyebrow":"MECANISMO DE AÇÃO","heading":"A dupla ação, na concentração que a ciência recomenda","intro":"Ketochlor® é indicado para o tratamento dos sinais clínicos relacionados às infecções secundárias associadas à DAC, promovendo a redução do prurido e da gravidade das lesões — principalmente nos casos agravados pela hiperproliferação de fungos e bactérias sensíveis à Clorexidina e ao Cetoconazol.","cetoconazol":{"titulo":"Cetoconazol 1%","subtitulo":"Ação antifúngica superior","corpo":"Penetração 7 a 14 vezes superior à do miconazol no estrato córneo². Alta afinidade pela queratina garante efeito residual prolongado e previne a recolonização². Maior espectro de ação antifúngica in vitro³."},"clorexidina":{"titulo":"Clorexidina 2,3%","subtitulo":"Controle bacteriano decisivo","corpo":"De acordo com o ISCAID (2025), a clorexidina em concentrações de 2% a 4% deve ser a principal escolha terapêutica tópica para cães¹. Ketochlor® foi formulado com a concentração ideal¹ em associação com antifúngico."},"closing":"Dois ativos. Uma diretriz internacional como validador."}'::jsonb),
  ('tecnologia_sis', '{"eyebrow":"TECNOLOGIA EXCLUSIVA VIRBAC","heading":"Tecnologia exclusiva SIS: além da ação antimicrobiana","body":"Ketochlor® é o único do mercado com a tecnologia exclusiva SIS — Skin Innovative Science™, a junção de duas tecnologias proprietárias Virbac: Glyco® e Defensin®⁴. Combinadas, elas auxiliam o equilíbrio do microbioma cutâneo e apoiam a manutenção de uma pele saudável — reforço que vai além do controle antifúngico e bacteriano, relevante especialmente para o paciente atópico, cuja barreira cutânea já está comprometida.","imagem":{"url":"/assets/anatomia-da-pele.png","alt":"Ilustração técnica das camadas da pele e folículo piloso"}}'::jsonb),
  ('prova_autoridade', '{"eyebrow":"PROVA DE AUTORIDADE","heading":"Resultados observados em estudo clínico Virbac","stats":[{"value":"70%","label":"dos cães com melhora clínica significativa dos sinais avaliados","pct":70},{"value":"63%","label":"redução média do prurido relatado pelos tutores","pct":63},{"value":"100%","label":"de satisfação dos tutores que testaram o produto*","pct":100}],"note":"Dados internos Virbac (\"data on file\")*, estudo com 41 cães. Racional científico apoiado em literatura publicada e revisada — ISCAID (2025)¹, Pershing et al. (1994)², Gupta et al. (2025)³.","selo":{"url":"/assets/padrao-ouro.png","alt":"Selo Padrão Ouro Virbac"},"ctaLabel":"QUERO ACESSAR O ESTUDO COMPLETO"}'::jsonb),
  ('protocolo', '{"eyebrow":"PROTOCOLO DE USO","heading":"Protocolo simples de prescrever","modoUso":"Aplicar duas vezes por semana. Massagear e deixar o produto agir na pelagem por 10 minutos antes de enxaguar. Duração do tratamento: 5 semanas, ou a critério do médico-veterinário.","estabilidadeBadge":"12 MESES DE ESTABILIDADE","closing":{"product":"Ketochlor®","highlight":"é o único do mercado com estabilidade de 12 meses após aberto","text":"Permitindo o tratamento completo, sem interrupção por perda de eficácia e sem desperdício para o tutor."},"dosagem":[{"peso":"< 4,99","volumeMl":"10"},{"peso":"5 – 10,99","volumeMl":"15"},{"peso":"11 – 15,99","volumeMl":"20"},{"peso":"16 – 20,99","volumeMl":"25"},{"peso":"21 – 30,99","volumeMl":"30"},{"peso":"31 – 45,99","volumeMl":"40"},{"peso":"> 46","volumeMl":"50"}]}'::jsonb),
  ('diferenciais', '{"eyebrow":"SÍNTESE COMPARATIVA","heading":"Por que Ketochlor®, em síntese","items":[{"titulo":"Eficácia antifúngica superior","corpo":"Cetoconazol com 7-14x mais penetração no estrato córneo e efeito residual prolongado²"},{"titulo":"Potência antisséptica otimizada","corpo":"2,3% de Clorexidina, dentro da concentração recomendada pelo ISCAID¹"},{"titulo":"Tecnologia exclusiva SIS","corpo":"Estimula as defesas naturais da pele – essencial para o paciente atópico⁴"},{"titulo":"Estabilidade incomparável","corpo":"Único com 12 meses de validade em uso – tratamento completo, sem desperdício"}]}'::jsonb),
  ('material_tecnico', '{"eyebrow":"ACESSO AO MATERIAL TÉCNICO","heading":"O material técnico completo sobre Ketochlor® está a um cadastro de distância.","subheading":"Indicação, mecanismo de ação e protocolo de prescrição, com acesso imediato após o cadastro.","ctaLabel":"QUERO ACESSAR O MATERIAL TÉCNICO COMPLETO","legal":"Cadastro rápido. Acesso imediato. Dados protegidos conforme LGPD.","imagemCapa":{"url":"/assets/ketochlor-img-campanha.png","alt":"Capa do Guia Técnico de Prescrição Ketochlor®"}}'::jsonb),
  ('cta_secundario', '{"heading":"Prefere conversar diretamente com a equipe Virbac?","body":"Deseja receber contato ou visita da equipe comercial? Marque essa opção no formulário acima.","ctaLabel":"SOLICITAR CONTATO"}'::jsonb),
  ('faq', '{"eyebrow":"FAQ TÉCNICO","heading":"Perguntas frequentes","perguntas":[{"question":"Ketochlor deve ser usado de forma contínua em cães com DAC?","answer":"Não. A recomendação da literatura é que, após o tratamento das infecções secundárias por 4 a 5 semanas, o paciente passe a usar um shampoo hidratante de forma contínua (como Allermyl®), retornando ao uso do Ketochlor somente se houver recidiva do processo infeccioso."},{"question":"Ketochlor® substitui o tratamento sistêmico da DAC?","answer":"Em geral, não. Nos casos de Dermatite Atópica, o tratamento tópico faz parte de um conjunto de cuidados necessários para reduzir recidivas e manter a qualidade de vida do paciente, aliado ao tratamento sistêmico, controle de ectoparasitas, mudanças na dieta, entre outros."},{"question":"Qual a diferença entre usar Ketochlor® e o Hexadene Spherulites®?","answer":"Enquanto Ketochlor possui uma combinação de 2 ingredientes (Clorexidina e Cetoconazol), sendo indicado em casos mais crônicos, em geral relacionados à Dermatite Atópica, o Hexadene é uma solução única (Clorexidina 3%), mais indicado em casos primários, mais simples ou casos agudos de piodermite."},{"question":"Por que a estabilidade de 12 meses após aberto importa clinicamente?","answer":"Garante que o produto mantenha eficácia ao longo do tratamento e retratamentos, sem perda por degradação — reduzindo desperdício."}]}'::jsonb)
on conflict (key) do update
  set data = excluded.data,
      updated_at = now();
